### ISSUE TITLE
Japanese only?

### ISSUE THREAD

**Issue by olso** [yosuke-furukawa/tower-of-babel#16]
As much as I'd love to learn Japanese :8ball:, maybe introduce i18n to project?
I will gladly help with translation.

https://github.com/yosuke-furukawa/tower-of-babel/blob/master/exercises/babel_setup/problem.md

**Comment by martinheidegger** [comment]
Took the liberty and started with it: https://github.com/yosuke-furukawa/tower-of-babel/pull/18

**Comment by yosuke-furukawa** [comment]
Yep, please wait.

**Comment by martinheidegger** [comment]
@olso Do you mind check-reading my translation (I bet its messy at some points)

**Comment by yosuke-furukawa** [comment]
#30 released.
