### ISSUE TITLE
not `let` but `var` ?

### ISSUE THREAD

**Issue by rochefort** [yosuke-furukawa/tower-of-babel#22]
https://github.com/yosuke-furukawa/tower-of-babel/blob/master/exercises/block_scope/solution/solution.js#L2

blockの外なのでvarなのかと思ったのですが、どうでしょうか？

**Comment by rochefort** [comment]
すいません、letでもいい気がしてきました。取り下げます。

**Comment by yosuke-furukawa** [comment]
コメントありがとうございます。
この問題の場合は var でも let でもどちらでも良いです。習慣的に let を使うようにしているので、こうしました。

ただし、 let は var と違って一個だけ注意が必要で、let は巻き上げが起こらないので、以下の様な時に let を使うとエラーになります。

```javascript
f(); // throws error
let x = 12;
function f() { return x } // tries to read local x
```

これを Temporary DeadZone と言います、こういう例の時は let じゃなくて var を使うべきですね。
ちなみにこの、TDZはbabelでは実装されていますが、フラグを付けないと有効になりません。

```shell
$ babel-node --optional es6.blockScopingTDZ hoge.js
```

長々と説明しましたが、 letとvarはブロックの中と外は無関係、ただし、 let に関しては巻上げが起こらないことに注意して使うほうが良い、という話です。
