### ISSUE TITLE
フィードバック

### ISSUE THREAD

**Issue by yosuke-furukawa** [yosuke-furukawa/tower-of-babel#5]
- 2問目、3問目、runやverifyするとエラーになります。昨日朝は通ってたので、0.1.2になってから?
Error: Cannot find module 'babel-runtime/helpers/create-class'

- 3問目 問題を解くために、superキーワードで親クラスのプロパティやメソッドを参照できるという知識が必要なので、その説明があると親切かなと思いました。

- 4問目 「Node.js/io.jsにはcommonjsが組み込みで使えていますが」→ 「Node.js/io.jsではcommonjsが組込みで使えますが」

- 4問目 commonjsはJSのモジュールまわりの仕組みの提案だと思いますが、知らない人もいると思うので、一言解説があると親切かなと思いました。

- 10問目模範解答で result += x となってますが、代入する必要はない気がするので、result + x でいいのでは?

- READMEに「Japanese exercise will move to tower-of-babel-jp」とありますが、workshopper 2.3.1であればI18N対応済みなのでひとつのモジュールで全言語対応できると思います。

- 上記と関連して、メニューや結果が英語で表示されるので、日本語用リソースを追加して日本語表示できるようにしたほうがいいですね。

**Comment by tgfjt** [comment]
> i18n
今だと ja は選べなくて en なのに日本語、という状態なので、
workshopperとしては、`tower-of-babel -l ja` で日本語になる、が正しい、ですかね。
（英語版作りが大変そうです :cry: ）

**Comment by yosuke-furukawa** [comment]
一旦i18n以外の問題は対応しました。i18nもやろうと思ったんですけど、ちょっと僕の知識不足なので後でやります。
