### ISSUE TITLE
Error on exercise 4 and 5: invalid arguments

### ISSUE THREAD

**Issue by nathanBrenner** [yosuke-furukawa/tower-of-babel#79]
Ran `tower-of-babel verify program.js`, and get error: 

`USAGE: tower-of-babel run|verify <executeFile> <importFile>
/usr/local/lib/node_modules/tower-of-babel/exercises/modules_default_export/exercise.js:14
    throw new Error("invalid arguments");`

The code I'm using matches the code in the solutions.  I'm betting this is in part of how Babel is set up as specified in the first exercise.  I tried setting it up as the Babel documentation recommends (locally, within the project), but I hit a different error.

**Comment by alexandreferreirafr** [comment]
nathan you should `run tower-of-babel verify program.js Math.js`

since the test expects 2 args : `USAGE: tower-of-babel run|verify <executeFile> <importFile>`
