### ISSUE TITLE
modules default exportsの説明について

### ISSUE THREAD

**Issue by teppeis** [yosuke-furukawa/tower-of-babel#8]
https://github.com/yosuke-furukawa/tower-of-babel/blob/v0.2.0/exercises/modules_default_export/problem.md

この例はdefault exportsの例としては意図が伝わりにくいと思いました。

```javascript
// export
export default {greeting: greeting, name: name, version: version};

// import
import Message from './Message';
console.log(Message.greeting + ' ' + Message.name + ' ' + Message.version);
```

これはdefaultを使わずにnamed exportsでこう書き直すこともできますよね。

```javascript
// export
export {greeting, name, version};

// import
import {greeting, name, version} from './Message';
console.log(greeting + ' ' + name + ' ' + version);
```

つまり本質的にはnamed exportsなのに、一旦オブジェクト化して、さらにdefaultにするっていう遠回りをやっているように見えます。

> また、importする側は、exportされている対象の名前を知る必要があります。

と書いているとおり、default exportsの利点は名前を知らなくて良いことなんですが、この例では`greeting, name, version`というプロパティの名前を知らないといけないというnamed exportsの特徴は変わってないです。

また、もし例のようなオブジェクトでもらいたいならimport側で解決すべきと思います。

```javascript
// import
import * as Message from './Message';
```
こちらの方がimportする利用者側に、オブジェクトでもらうか、個別にもらうか、リネームしてもらうかの選択の自由があります。冒頭のdefault object式だと選択できないので。

defaultの例を作るとしたら、やっぱりexportごとにファイル分割するのが良いと思います。今回の例がそれに適しているかはさておき。

**Comment by yosuke-furukawa** [comment]
@teppeis ありがとうございます！ちょっと今日直して PR 上げておく予定です。もしお時間あれば再読のほど、よろしくお願いいたします。

**Comment by yosuke-furukawa** [comment]
#9 

また何かあればお願い致します m(_ _)m
