### ISSUE TITLE
Error: Could not run: EPERM: operation not permitted

### ISSUE THREAD

**Issue by sandip8600** [yosuke-furukawa/tower-of-babel#81]
I am trying to run BABEL SETUP tutorial But I'm getting error `, symlink 'C:\Users\user\AppData\Roaming\npm\node_modules\tower-of-babel\node_modules' -> 'C:\Users\user \AppData\Local\Temp\_babel_6612\node_modules'`

**Comment by leader22** [comment]
Same error happened in nodeschool at 11/12 too.

But timing was different, in our case, `tower-of-babel verify program.js`.

**Comment by elios264** [comment]
You need to run the command as Admin
